// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAc7HcU4VVLpl6Q1RKpCiwBzvqm3FCR3w',
    appId: '1:118248156698:web:6dacf83740749ed351aba3',
    messagingSenderId: '118248156698',
    projectId: 'flutter-web-app1-81b15',
    authDomain: 'flutter-web-app1-81b15.firebaseapp.com',
    storageBucket: 'flutter-web-app1-81b15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlN7Up5U7JS6s3fPzBjTd_WmsDGch4G9g',
    appId: '1:118248156698:android:3d5dbd96294871cc51aba3',
    messagingSenderId: '118248156698',
    projectId: 'flutter-web-app1-81b15',
    storageBucket: 'flutter-web-app1-81b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX2mBp0FjX0L31qoBfeJWI1DUR_O6pMKs',
    appId: '1:118248156698:ios:4c7229d374eb010e51aba3',
    messagingSenderId: '118248156698',
    projectId: 'flutter-web-app1-81b15',
    storageBucket: 'flutter-web-app1-81b15.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX2mBp0FjX0L31qoBfeJWI1DUR_O6pMKs',
    appId: '1:118248156698:ios:4c7229d374eb010e51aba3',
    messagingSenderId: '118248156698',
    projectId: 'flutter-web-app1-81b15',
    storageBucket: 'flutter-web-app1-81b15.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAc7HcU4VVLpl6Q1RKpCiwBzvqm3FCR3w',
    appId: '1:118248156698:web:eabfaee24c8401fd51aba3',
    messagingSenderId: '118248156698',
    projectId: 'flutter-web-app1-81b15',
    authDomain: 'flutter-web-app1-81b15.firebaseapp.com',
    storageBucket: 'flutter-web-app1-81b15.firebasestorage.app',
  );
}
